language: node_js
node_js:
  - 6.4.0
branches:
  only:
    - master
before_install:
  - npm install -g hexo hexo-cli
install:
  - npm install
before_script:
  - git config --global user.name 'chrismarksus'
  - git config --global user.email 'chrismarksus@gmail.com'
script:
  - hexo generate
after_success:
  - cd public
  - git init
  - git add .
  - git commit -m "Deploy to Github Pages (`date`)"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/${GH_REPO}.git" master:gh-pages
env:
  global:
    - secure: >-
        Q999LlwWRxah4VfzlgEtMZImtLwMrfCrQm6EUYhhY4eaLw7UQXMbqiDKAAVC1c2UOijAjO4pJawWOYri7E746xYoqbN5VaBQgwYFRcyM/ZDUjMh0Xw2tga/PiJihgQMSO7aK4puY0yMsw5H7b15Om6fDLUWxhvaN+7z4K1umxV9OOt/zsyQA5NaVE0FFlVkD+uzSbvHeheX3RNpi3OvhNrdQZ9yRbutn2gixNJi/qvCj+/ir8nx/8Ey3WQV7t/kN+Xky0SVr1aVpZi754c6xrTud5nQJRW/DEB31LRAadz2Ff8wjX2rfh+OY+qbPWlDVD33x/d3/Nfxhq8f0xcF1yWzTX/X/yHwQunJWYLMDbtHqdptFdKMRY97pn9R7eeNQJOOEMARIFTZr6fS2SSKUUk7Wko9q2kICelzSni9JHZl3jU7JAe4xOOaC3crVpVqfgcK6DzoXGGj33K/8OfCWJgZto/TOPd4BneRU+WLmMhtSy9aTSMpJUVbLddRWrRIjhONyukHaSixbL8TB0+rzGrrg/KIeOSl1nSZeo9ZoE3XkO55Q3lQa3v/JlMlKMxG9ibhn4wGhRAB6g0sp5jdzBAez709ikeE0aayqki8fYxEVAhBjwZOFKQ4E/gXuYanLEuFlP0/Lh12htZMSpOebjB8vOSqWydVB/OC9GK9tpHg=
