language: node_js

node_js:
    - "6.4.0"

sudo: false

before_install:
    - npm install -g hexo

install:
    - npm install

before_script:
    - git config --global user.name 'chrismarksus'
    - git config --global user.email 'chrismarksus@gmail.com'

script:
    - hexo generate

env: CI=true
